apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-cert
  namespace: apps
spec:
  secretName: apps-cert
  dnsNames:
    - cristianaldea.com
    - www.cristianaldea.com
    - apps.cristianaldea.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
